12 3 search text on site
thinknetica-django-lab-02/Th0rn-dev pull request #110
Opened 2021-05-03 18:43 UTC by Th0rn-dev

Closes #87

2021-05-04 10:01 UTC, mikhailborodin requested changes

2021-05-04 10:01 UTC, mikhailborodin commented on booking/main/views.py
> +            for tag in room.tags:
надо избегать вложенные циклы, можно получить все тэги комнат по-другому, например, так `Room.objects.prefetch_related('tag').values_list('tag_name', flat=True)`

2021-05-05 05:46 UTC, Th0rn-dev commented on booking/main/views.py
> +            for tag in room.tags:
Михаил, в этой задаче для атрибута tags связь meny_to_many заменена на ArrayField, во вложенном цикле уже нет запросов к базе. Сибираю в set все теги, чтобы отобразить их во вьюшке

2021-05-06 06:11 UTC, mikhailborodin approved these changes

2021-05-06 08:23 UTC, merged